services:
  - type: web
    name: proyecto-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    rootDir: .
    envVars:
      - key: DB_HOST
        value: <tu-host-de-base-de-datos>
      - key: DB_USER
        value: <tu-usuario-de-bd>
      - key: DB_PASS
        value: <tu-contraseÃ±a-de-bd>
      - key: DB_NAME
        value: proyecto_db
      - key: JWT_SECRET
        value: clave_super_segura
